blank_issues_enabled: true
contact_links:
  - name: Ask a question ❓
    url: https://github.com/shakers-xyz/sh-verified-skeleton-java-spring-rest/discussions/new
    about: Ask a question or request support for using this skeleton
